/** Generated by scripts/generate-from-config.mjs — edit templates/clinic.config.json and re-run generate. */

export type AdminRole = "owner" | "staff";

export interface AdminAccount {
  id: string;
  email: string;
  name: string;
  role: AdminRole;
}

/** Staff accounts — passwords come from environment variables only. */
export const adminAccounts: AdminAccount[] = [
  {
    id: "owner",
    email: "owner",
    name: "Clinic Owner",
    role: "owner",
  },
  {
    id: "staff",
    email: "staff",
    name: "Front Desk",
    role: "staff",
  },
];

export function getAdminAccountByEmail(email: string): AdminAccount | undefined {
  const normalized = email.trim().toLowerCase();
  return adminAccounts.find((account) => account.email.toLowerCase() === normalized);
}

export function getAdminAccountById(id: string): AdminAccount | undefined {
  return adminAccounts.find((account) => account.id === id);
}

export function canManageClinicSettings(_role: AdminRole): boolean {
  return true;
}

export function getRoleLabel(role: AdminRole): string {
  return role === "owner" ? "Owner" : "Front Desk";
}
