/** Generated by scripts/generate-from-config.mjs — edit templates/clinic.config.json and re-run generate. */

export type AdminRole = "owner" | "staff" | "dentist";

export interface AdminAccount {
  id: string;
  email: string;
  name: string;
  role: AdminRole;
  /** Links dentist login to operational dentist record. */
  linkedDentistId?: string;
}

export const adminAccounts: AdminAccount[] = [
  {
    id: "owner",
    email: "owner",
    name: "Clinic Owner",
    role: "owner",
  },
  {
    id: "staff",
    email: "staff",
    name: "Front Desk",
    role: "staff",
  },
  {
    id: "dentist-chen",
    email: "dr-chen",
    name: "Dr. Sarah Chen",
    role: "dentist",
    linkedDentistId: "dr-chen",
  },
  {
    id: "dentist-patel",
    email: "dr-patel",
    name: "Dr. Raj Patel",
    role: "dentist",
    linkedDentistId: "dr-patel",
  },
];

export function getAdminAccountByEmail(email: string): AdminAccount | undefined {
  const normalized = email.trim().toLowerCase();
  return adminAccounts.find((account) => account.email.toLowerCase() === normalized);
}

export function getAdminAccountById(id: string): AdminAccount | undefined {
  return adminAccounts.find((account) => account.id === id);
}

export function canManageClinicSettings(role: AdminRole): boolean {
  return role === "owner";
}

export function canViewAnalytics(role: AdminRole): boolean {
  return role === "owner";
}

export function canManageAppointments(role: AdminRole): boolean {
  return role === "owner" || role === "staff";
}

export function canCreateStaffBookings(role: AdminRole): boolean {
  return role === "owner" || role === "staff";
}

export function isDentistRole(role: AdminRole): boolean {
  return role === "dentist";
}

export function getRoleLabel(role: AdminRole): string {
  if (role === "owner") return "Owner";
  if (role === "staff") return "Front Desk";
  return "Dentist";
}

/** Owner-only admin routes. */
export const OWNER_ONLY_PATHS = [
  "/admin/hours",
  "/admin/dentists",
  "/admin/schedule",
] as const;

export function isOwnerOnlyPath(pathname: string): boolean {
  return OWNER_ONLY_PATHS.some(
    (path) => pathname === path || pathname.startsWith(`${path}/`)
  );
}

/** Staff/owner routes dentists should not access. */
export function isStaffOnlyPath(pathname: string): boolean {
  if (isOwnerOnlyPath(pathname)) return true;
  return pathname === "/admin/book" || pathname.startsWith("/admin/book/");
}

export function getDefaultAdminPath(role: AdminRole): string {
  return role === "dentist" ? "/admin/my-day" : "/admin";
}
