/** Generated by scripts/generate-from-config.mjs — edit templates/clinic.config.json and re-run generate. */

export const lorem = {
  short: "Professional dental care with online booking and friendly staff.",
  medium: "Book appointments online, get email confirmations, and visit a clinic designed for busy families and working professionals.",
  long: "Our clinic combines modern dentistry with a warm, local feel. Online booking, clear pricing conversations, and a staff dashboard keep visits organized from first call to follow-up.",
  quote: "The team was patient, thorough, and made my first visit easy. Booking online saved me time and the reminders were helpful.",
  paragraphs: [
    "We are a neighborhood dental clinic built around comfort, clarity, and consistent care. From check-ups to cosmetic work, our team explains every step in plain language.",
    "Our reception desk confirms appointments quickly, and patients can book or reschedule online anytime. We treat families, professionals, and first-time visitors with the same attention.",
    "Whether you need a cleaning, filling, braces consult, or emergency visit, we focus on gentle treatment and long-term oral health.",
  ],
  contact: {
    address: "123 Commonwealth Ave, Brgy. Holy Spirit, Quezon City",
    landmark: "Near SM North EDSA",
    phones: [
      "0917 123 4567",
      "02 8812 3456",
    ],
    email: "hello@smilecare.ph",
  },
} as const;
