/** Generated by scripts/generate-from-config.mjs — edit templates/clinic.config.json and re-run generate. */

import { lorem } from "./lorem";

export const site = {
  name: "SmileCare Dental Clinic",
  shortName: "SmileCare",
  tagline: "Your smile, our passion",
  type: "dental clinic",
  description: "Family-friendly dental care with online booking, gentle treatment, and a team focused on healthy smiles for every age.",
  location: {
    city: "Quezon City",
    province: "Metro Manila",
    country: "Philippines",
    full: "123 Commonwealth Ave, Brgy. Holy Spirit, Quezon City",
    landmark: "Near SM North EDSA",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3859.5!2d121.043!3d14.676!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTTCsDQwJzMzLjYiTiAxMjHCsDAyJzM0LjgiRQ!5e0!3m2!1sen!2sph!4v1",
    coordinates: {
      lat: 14.676,
      lng: 121.043,
    },
  },
  contact: {
    phones: [
      "0917 123 4567",
      "02 8812 3456",
    ],
    email: "hello@smilecare.ph",
    facebook: "https://facebook.com/smilecaredental",
  },
  hours: {
    summary: "Mon–Sat 9 AM–5 PM, Sunday by appointment",
    schedule: [
      {
        days: "Monday – Friday",
        hours: "9:00 AM – 5:00 PM",
      },
      {
        days: "Saturday",
        hours: "9:00 AM – 5:00 PM",
      },
      {
        days: "Sunday",
        hours: "By appointment only",
      },
    ],
  },
  brand: {
    primary: "#3B7A5C",
    accent: "#D4729B",
    dark: "#1A3C34",
    cream: "#FAF7F2",
    surface: "#F4F1EC",
  },
  social: {
    rating: 4.9,
    reviewCount: 240,
    patientCount: "2,500+",
  },
} as const;

export type Site = typeof site;
