/** Escape a string for use inside double-quoted TS literals. */
export function tsString(value) {
  return JSON.stringify(String(value ?? ""));
}

/** Format a JS value as indented TS literal source. */
export function tsValue(value, indent = 0) {
  const pad = "  ".repeat(indent);
  const padInner = "  ".repeat(indent + 1);

  if (value === null || value === undefined) return "undefined";
  if (typeof value === "string") return tsString(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((item) => `${padInner}${tsValue(item, indent + 1)}`).join(",\n");
    return `[\n${items},\n${pad}]`;
  }

  const entries = Object.entries(value);
  if (entries.length === 0) return "{}";
  const lines = entries.map(
    ([key, val]) => `${padInner}${/^[a-zA-Z_$][\w$]*$/.test(key) ? key : tsString(key)}: ${tsValue(val, indent + 1)}`,
  );
  return `{\n${lines.join(",\n")},\n${pad}}`;
}

export function fileHeader(source = "scripts/generate-from-config.mjs") {
  return `/** Generated by ${source} — edit templates/clinic.config.json and re-run generate. */\n\n`;
}
